### ISSUE TITLE
How I can ignore the test folder?

### ISSUE THREAD

**Issue by suportebeloj** [greenbone/autohooks-plugin-pylint#381]
I'm trying to ignore a test folder that is present in the root of the project, however, pylint is completely ignoring the settings file and _pyproject.toml_

_pyproject.toml_
```
[tool.autohooks.plugins.pylint]
arguments = ["--rcfile=.pylintrc", '-sn']
```

_.pylintrc_
`ignore-paths=tests`

_stdout_
```
ℹ autohooks => pre-commit
     ℹ Running autohooks.plugins.black
         ✓ Running black on tests/test_app_scheduler.py
     ℹ Running autohooks.plugins.pylint
         × Linting error(s) found in tests/test_app_scheduler.py:
         tests/test_app_scheduler.py:1:0: C0114: Missing module docstring (missing-module-docstring)
         tests/test_app_scheduler.py:4:0: C0116: Missing function or method docstring (missing-function-docstring)
```

**Comment by bjoernricks** [comment]
Hi, did you try it without setting `"--rcfile=.pylintrc"` explicitly? the file is considered by pylint automatically. We are using it in all our Python repos in that way.

**Comment by suportebeloj** [comment]
sorry, still having problems, implemented a hook manually to solve this as well as adding a comment to disable the alerts in the test files

**Comment by bjoernricks** [comment]
Hi, I just want to mention again that we are using a dedicated `.pylintrc` file for all of our Python repos and it's picked up during the pre commit hook. This seems to me to be more a general pylint issue. Maybe the `ignore` setting works instead.
